// urls.js

const urls = [
  'https://topart.ai/',
  'https://autoshorts.ai/',
  'https://www.kapwing.com/',
  'https://www.deepbrain.io/',
  'https://www.pipio.ai/',
  'https://www.myarchitectai.com/',
  'https://vivago.ai/video?type=txt2video',
  'https://www.digen.ai/',
  'https://replicate.com/fofr',
  'https://www.revid.ai/',
  'https://www.videofast.app/',
  'https://virbo.wondershare.com/',
  'https://www.upscale.media/',
  'https://letz.ai/',
  'https://www.photoroom.com/',
  'https://www.colossyan.com/',
  'https://odyssey.systems/',
  'https://www.captions.ai/',
  'https://huggingface.co/spaces/KwaiVGI/LivePortrait',
  'https://gan.ai/',
  'https://x.com/augiestudio',
  'https://www.profilepicture.ai/',
  'https://ossa.ai/',
  'https://huggingface.co/alvdansen/frosting_lane_redux',
  'https://apob.ai/',
  'https://www.dreamflare.ai/',
  'https://haiper.ai/home',
  'https://x.com/ArtDotTech',
  'https://www.freepik.com/pikaso/ai-image-generator',
  'https://productscope.ai/',
  'https://www.viggle.ai/',
  'https://www.artbreeder.com/',
  'https://deepai.org/',
  'https://looka.com/',
  'https://pixverse.ai/',
  'https://www.gendo.ai/',
  'https://www.rephrase.ai/',
  'https://www.vidu.studio/',
  'https://replicate.com/blog/flux-first-impressions',
  'https://ideogram.ai/',
  'https://clapper.app/',
  'https://enigmaproject.ai/',
  'https://peerlist.io/aykutkardas/project/mindtown-ai',
  'https://aiflux.cc/',
  'https://lora.gallery/',
  'https://discopixel.app/animator',
  'https://huggingface.co/spaces/Kwai-Kolors/Kolors-Virtual-Try-On',
  'https://anifusion.ai/',
  'https://hailuoai.com/video',
  'https://playground.com/'
];

export default urls;
